In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_pickle('../Extracted_Information.dat')
worldmap = pd.read_csv('../world_bank_country_mappings.csv')
gdp_historical = pd.read_csv('../gdp91-21.csv')

In [3]:
data.head()

,filename,Date,Project_name,Currency,Amount_loan,Amount_in_usd,Project_desc,Country_code,Address,Country3code,Country_name,Income_level,Region
0,1990_april_24_587321468019152780_conformed-cop...,1990-04-24 00:00:00,forestry sector project,$,80000000,80000000,Description of the Project The objectives of t...,IVC,"\n\nministry of economy, finance and budget\np...",CIV,Cote d'Ivoire,Lower middle income,Sub-Saharan Africa (excluding high income)
1,1990_april_24_668811468165272290_conformed-cop...,1990-04-24 00:00:00,water supply project,$,2500000,2500000,,SLU,"\n\n ministry of planning, personnel,\n est...",LCA,St. Lucia,Upper middle income,Latin America & Caribbean (excluding high income)
2,1990_april_25_904191468298750561_conformed-cop...,1990-04-25 00:00:00,environment management project,$,18000000,18000000,Description of the Project The objectives of t...,POL,"\n\n ministry of environmental protection,\n ...",POL,Poland,High income,NaN
3,1990_april_30_410811468040573756_conformed-cop...,1990-04-30 00:00:00,rural electrification project,$,329000000,329000000,Description of the Project The objective of th...,IND,\n\n ministry of finance\n c/o directorate...,IDN,Indonesia,Upper middle income,East Asia & Pacific (excluding high income)
4,1990_april_30_725911468042268845_conformed-cop...,1990-04-30 00:00:00,third telecommunications project,$,350000000,350000000,Description of the Project The objectives of t...,IND,\n\n ministry of finance\n c/o director ge...,IDN,Indonesia,Upper middle income,East Asia & Pacific (excluding high income)

In [6]:
gdp_historical.head()

  LOCATION INDICATOR SUBJECT  MEASURE FREQUENCY  TIME         Value Flag Codes
0      AUS       GDP     TOT  USD_CAP         A  1991  18126.137999        NaN
1      AUS       GDP     TOT  USD_CAP         A  1992  19094.496782        NaN
2      AUS       GDP     TOT  USD_CAP         A  1993  20118.480443        NaN
3      AUS       GDP     TOT  USD_CAP         A  1994  21349.565284        NaN
4      AUS       GDP     TOT  USD_CAP         A  1995  22353.994564        NaN

In [5]:
data.Date[0].year

1990

In [9]:
gdp_value = []
for i in data.index:
    country = data.Country3code[i]
    time = data.Date[i].year
    gdp = 0
    for j in gdp_historical.index:
        if gdp_historical.LOCATION[j] == country:
            for k in range(j,j+30):
                if gdp_historical.TIME[k] == time:
                    gdp = gdp_historical.Value[k]
                    break
    gdp_value.append(gdp)

In [10]:
len(gdp_value)

3205

In [11]:
gdp_value

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 20102.246439,
 0,
 0,
 22348.029429,
 36717.303718,
 0,
 0,
 5557.82789,
 5557.82789,
 5200.78712,
 12700.582427,
 25570.900782,
 25570.900782,
 25570.900782,
 25570.900782,
 25570.900782,
 25570.900782,
 25570.900782,
 25570.900782,
 25570.900782,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 5200.78712,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 5557.82789,
 0,
 0,
 0,
 0,
 0,
 36717.303718,
 0,
 0,
 5200.78712,
 20102.246439,
 0,
 5200.78712,
 0,
 0,
 0,
 5200.78712,
 0,
 0,
 5200.78712,
 12700.582427,
 12700.582427,
 0,
 0,
 0,
 5200.78712,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 12700.582427,
 0,
 22348.029429,
 0,
 0,
 5200.78712,
 25570.900782,
 25570.900782,
 5200.78712,
 0,
 0,
 20102.246439,
 20102.246439,
 12700.582427,
 12700.582427,
 12700.582427,
 12700.582427,
 0,
 0,
 5200.78712,
 5200.78712,
 0,
 0,
 20102.246439,
 0,
 5200.78712,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 6545.666776,
 0,
 0,
 0,
 25570.900782,
 25570.900782,
 0,
 0,
 5200.78712,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 25570.900782,
 5200.78712,
 5200.78712,
 0,
 0,
 0,
 0,
 17314.530887,
 17314.530887,
 17314.530887,
 12700.582427,
 12700.582427,
 0,
 12700.582427,
 12700.582427,
 12700.582427,
 12700.582427,
 0,
 0,
 25570.900782,
 0,
 0,
 21820.702176,
 27061.474860000002,
 21820.702176,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1256.147371,
 0,
 5441.441062,
 5441.441062,
 0,
 37903.27627,
 0,
 5441.441062,
 0,
 0,
 0,
 0,
 0,
 5441.441062,
 0,
 0,
 0,
 0,
 13136.826692,
 5441.441062,
 13136.826692,
 0,
 5441.441062,
 0,
 0,
 0,
 5441.441062,
 0,
 0,
 0,
 0,
 20754.114426,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 6411.898523,
 0,
 0,
 5441.441062,
 0,
 37903.27627,
 0,
 0,
 0,
 5777.756783,
 0,
 0,
 6518.413515,
 0,
 22401.161183,
 22401.161183,
 13158.63288,
 0,
 30113.891058999998,
 0,
 0,
 0,
 4772.398486,
 6504.259602,
 0,
 0,
 0,
 6504.259602,
 14860.725586000002,
 5777.756783,
 5777.756783,
 13158.63288,
 4772.398486,
 30113.891058999998,
 5777.756783,
 0,
 0,
 5777.756783,
 0,
 0,
 0,
 0,
 5725.0865189999995,
 0,
 0,
 0,
 0,
 30113.891058999998,
 6518.413515,
 0,
 5777.756783,
 5777.756783,
 0,
 5777.756783,
 0,
 0,
 4772.398486,
 4772.398486,
 0,
 0,
 0,
 0,
 22401.161183,
 0,
 0,
 4772.398486,
 30113.891058999998,
 30113.891058999998,
 30113.891058999998,
 30113.891058999998,
 30113.891058999998,
 30113.891058999998,
 30113.891058999998,
 5777.756783,
 4772.398486,
 4772.398486,
 0,
 0,
 0,
 0,
 0,
 0,
 5777.756783,
 4772.398486,
 0,
 18565.700177000002,
 18565.700177000002,
 0,
 22401.161183,
 0,
 0,
 0,
 4772.398486,
 0,
 6504.259602,
 0,
 4772.398486,
 0,
 4772.398486,
 4772.398486,
 4772.398486,
 4772.398486,
 20178.829135,
 0,
 13158.63288,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 13158.63288,
 5169.582915999999,
 6122.683411,
 6122.683411,
 6122.683411,
 5169.582915999999,
 5169.582915999999,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 5169.582915999999,
 21836.544499,
 6122.683411,
 5884.861897,
 0,
 0,
 0,
 0,
 0,
 0,
 5884.861897,
 5169.582915999999,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1652.916985,
 0,
 33110.834035,
 0,
 0,
 0,
 0,
 37306.572024,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 22330.337233000002,
 23507.096749,
 15511.967913999999,
 0,
 1652.916985,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 22330.337233000002,
 0,
 0,
 22330.337233000002,
 0,
 6122.683411,
 5169.582915999999,
 5169.582915999999,
 5169.582915999999,
 5169.582915999999,
 5169.582915999999,
 5169.582915999999,
 5169.582915999999,
 5169.582915999999,
 0,
 0,
 1652.916985,
 1652.916985,
 6122.683411,
 0,
 0,
 5169.582915999999,
 5169.582915999999,
 0,
 0,
 0,
 0,
 0,
 0,
 5169.582915999999,
 0,
 5169.582915999999,
 0,
 0,
 0,
 0,
 5169.582915999999,
 0,
 5169.582915999999,
 0,
 0,
 33110.834035,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 6122.683411,
 6122.683411,
 0,
 0,
 0,
 0,
 0,
 0,
 5169.582915999999,
 6122.683411,
 0,
 5169.582915999999,
 0,
 5169.582915999999,
 22330.337233000002,
 22330.337233000002,
 5169.582915999999,
 0,
 0,
 0,
 0,
 0,
 6122.683411,
 0,
 6760.64364,
 6760.64364,
 6122.683411,
 0,
 0,
 23507.096749,
 5169.582915999999,
 0,
 22330.337233000002,
 0,
 6122.683411,
 0,
 5169.582915999999,
 0,
 5169.582915999999,
 5169.582915999999,
 0,
 0,
 33110.834035,
 0,
 37306.572024,
 0,
 0,
 0,
 0,
 5169.582915999999,
 5169.582915999999,
 5169.582915999999,
 5169.582915999999,
 0,
 0,
 0,
 6122.683411,
 0,
 0,
 5169.582915999999,
 13536.716477000002,
 5169.582915999999,
 5169.582915999999,
 0,
 0,
 0,
 13536.716477000002,
 0,
 0,
 0,
 0,
 5169.582915999999,
 0,
 5169.582915999999,
 13536.716477000002,
 0,
 13536.716477000002,
 0,
 0,
 0,
 0,
 0,
 6760.64364,
 0,
 5169.582915999999,
 0,
 6122.683411,
 6122.683411,
 6122.683411,
 6122.683411,
 0,
 0,
 0,
 0,
 0,
 5169.582915999999,
 0,
 0,
 0,
 0,
 0,
 5169.582915999999,
 0,
 6122.683411,
 0,
 37304.286614,
 0,
 0,
 19966.219859,
 6405.567804,
 17055.098745,
 13602.803998,
 0,
 13602.803998,
 13602.803998,
 6475.32925,
 13602.803998,
 6475.32925,
 6475.32925,
 17055.098745,
 0,
 0,
 19966.219859,
 6475.32925,
 35159.633523000004,
 6475.32925,
 6475.32925,
 23389.334808,
 0,
 0,
 0,
 0,
 23389.334808,
 0,
 0,
 0,
 35159.633523000004,
 0,
 35159.633523000004,
 0,
 6475.32925,
 0,
 6986.959286,
 0,
 0,
 5916.118581000001,
 6475.32925,
 0,
 6475.32925,
 6405.567804,
 6475.32925,
 6475.32925,
 0,
 0,
 6986.959286,
 19966.219859,
 0,
 0,
 5633.1101530000005,
 0,
 37304.286614,
 0,
 1852.7818989999998,
 17055.098745,
 13602.803998,
 6475.32925,
 19966.219859,
 6475.32925,
 6475.32925,
 5416.727537,
 0,
 0,
 0,
 19966.219859,
 6475.32925,
 0,
 5633.1101530000005,
 23389.334808,
 0,
 0,
 6986.959286,
 0,
 0,
 5633.1101530000005,
 37304.286614,
 37304.286614,
 0,
 0,
 0,
 5916.118581000001,
 0,
 0,
 19966.219859,
 19966.219859,
 19966.219859,
 5916.118581000001,
 5916.118581000001,
 6475.32925,
 6475.32925,
 37304.286614,
 0,
 6986.959286,
 6986.959286,
 6986.959286,
 35159.633523000004,
 0,
 0,
 0,
 0,
 5633.1101530000005,
 5633.1101530000005,
 6986.959286,
 35159.633523000004,
 0,
 13602.803998,
 13602.803998,
 5633.1101530000005,
 0,
 0,
 0,
 0,
 19966.219859,
 6475.32925,
 6475.32925,
 19966.219859,
 23902.718765999998,
 19966.219859,
 6475.32925,
 0,
 0,
 6475.32925,
 5633.1101530000005,
 0,
 19966.219859,
 23389.334808,
 23389.334808,
 6475.32925,
 6475.32925,
 5916.118581000001,
 5916.118581000001,
 19966.219859,
 5916.118581000001,
 5916.118581000001,
 5916.118581000001,
 19966.219859,
 0,
 13602.803998,
 0,
 0,
 20502.823096,
 35159.633523000004,
 0,
 0,
 0,
 19966.219859,
 0,
 0,
 5633.1101530000005,
 5633.1101530000005,
 5633.1101530000005,
 6986.959286,
 5633.1101530000005,
 5633.1101530000005,
 5633.1101530000005,
 5633.1101530000005,
 0,
 0,
 23050.467255,
 0,
 0,
 0,
 0,
 0,
 0,
 13602.803998,
 17055.098745,
 0,
 0,
 0,
 13602.803998,
 19966.219859,
 0,
 0,
 0,
 0,
 5916.118581000001,
 19966.219859,
 19966.219859,
 0,
 6475.32925,
 6475.32925,
 20502.823096,
 6475.32925,
 0,
 13602.803998,
 0,
 0,
 0,
 0,
 6986.959286,
 0,
 0,
 6986.959286,
 1852.7818989999998,
 0,
 6405.567804,
 6405.567804,
 6405.567804,
 6405.567804,
 23050.467255,
 6986.959286,
 6986.959286,
 0,
 6986.959286,
 14371.63835,
 6475.32925,
 6475.32925,
 6475.32925,
 0,
 13602.803998,
 0,
 0,
 0,
 0,
 0,
 0,
 6986.959286,
 6986.959286,
 0,
 6986.959286,
 0,
 23902.718765999998,
 0,
 13602.803998,
 0,
 1852.7818989999998,
 0,
 0,
 0,
 5916.118581000001,
 5633.1101530000005,
 0,
 23389.334808,
 0,
 0,
 0,
 0,
 0,
 7995.711803,
 0,
 6593.758186,
 0,
 17277.539872999998,
 17277.539872999998,
 17277.539872999998,
 20830.398369,
 20830.398369,
 20830.398369,
 20830.398369,
 20830.398369,
 6593.758186,
 0,
 14264.321803,
 14264.321803,
 0,
 0,
 6099.4856119999995,
 0,
 0,
 24716.28379,
 0,
 0,
 0,
 0,
 0,
 0,
 6369.880929,
 17277.539872999998,
 6593.758186,
 0,
 20830.398369,
 20830.398369,
 0,
 6820.075318000001,
 20830.398369,
 0,
 0,
 0,
 0,
 14885.045863,
 6369.880929,
 6593.758186,
 6593.758186,
 6099.4856119999995,
 6099.4856119999995,
 0,
 0,
 0,
 0,
 0,
 ...]

In [12]:
for i in range(len(gdp_value)):
    if gdp_value[i] == 0:
        gdp_value[i] = None

In [13]:
data["GDP_historic"] = pd.Series(gdp_value)

In [16]:
data.to_csv('gdp.csv')